---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-anime
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-anime
    template:
      data:
        api_key: "{{ .api_key }}"
        config: |
          <Config>
            <BindAddress>*</BindAddress>
            <SslPort>9898</SslPort>
            <EnableSsl>False</EnableSsl>
            <LaunchBrowser>True</LaunchBrowser>
            <SslCertPath></SslCertPath>
            <SslCertPassword></SslCertPassword>
            <UrlBase></UrlBase>
            <UpdateMechanism>Docker</UpdateMechanism>

            <PostgresHost>{{ .DB_HOST }}</PostgresHost>
            <PostgresMainDb>{{ .DB_DATABASE }}</PostgresMainDb>
            <PostgresUser>{{ .DB_USER }}</PostgresUser>
            <PostgresPassword>{{ .DB_PASSWORD }}</PostgresPassword>
            <PostgresPort>5432</PostgresPort>
          </Config>

  dataFrom:
    - extract:
        key: "sonarr-anime.fem.arpa"
