---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-anime
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-anime
    template:
      data:
        api_key: "{{ .api_key }}"
  dataFrom:
    - extract:
        key: "API sonarr-anime.fem.arpa"
